---
- hosts: ings_vps
  sudo: yes
  # 変数定義
  vars:
    www_dir: '/var/www/html'
    repo_dir: 'repository.git'
    domain: 'xxx.xxx'
    docroot: 'htdocs'
    user: 'xxx'
    group: 'apache'
  # インタラクティブに聞かれる変数
  vars_prompt:
    # サブドメイン名
    subdomain: "Enter Subdomain Name"
    # 案件の接頭辞（DBのprefix,wordpressディレクトリに使用）
    prefix: "Enter Prefix"
    # ベーシック認証のパスワード
    authpasswd: "Enter Basic Authentication Password"
    # MySQLのrootパスワード
    root_dbpass: "Enter MySQL Root Password"
    # 今回作成するDBのパスワード
    dbpass: "Enter Wordpress Database Password"
    # wordpressの管理者メールアドレス
    email: "Enter Your Name => Send Mail To < name >@xxxx.co.jp"

  tasks:
    # サブドメインのディレクトリ＆ドキュメントルートのディレクトリを作成
    - include: tasks/create_root_directory.yml

    # ベーシック認証の設定
    - include: tasks/set_apache_basicauth.yml

    # wordpressの格納ディレクトリを作成
    - include: tasks/wp_create_directory.yml

    # Git リポジトリの作成
    - include: tasks/create_git_repository.yml

    # wordpress用データベースの作成
    - include: tasks/wp_create_database.yml

    # wp-cliを使用し、wordpressのコアファイルを取得、wp-config.phpを作成
    - include: tasks/wp_download_and_config.yml

    #wordpressをサブディレクトリにインストールするため、index.phpをドキュメントルートへコピー、index.php内のパスを編集
    - include: tasks/wp_subdirectory_setting.yml

    # wp-config.phpの編集
    - include: tasks/wp_edit_config.yml

    # wp-cliを使用し、wordpressのインストール
    - include: tasks/wp_install.yml

