---
- hosts: ings_vps
  sudo: yes
  # 変数定義
  vars:
    www_dir: '/var/www/html'
    wp_dir: 'wp'
    repo_dir: 'repository.git'
    domain: 'ingsnet.info'
    docroot: 'htdocs'
    user: 'ings'
    group: 'apache'
  # インタラクティブに聞かれる変数
  vars_prompt:
    subdomain: "Enter Subdomain Name"
    authpasswd: "Enter Basic Authentication Password"
  tasks:
    # サブドメインのディレクトリ＆ドキュメントルートのディレクトリを作成
    - include: tasks/create_root_directory.yml

    # ベーシック認証の設定
    - include: tasks/set_apache_basicauth.yml

    # Git リポジトリの作成
    - include: tasks/create_git_repository.yml

    # Git Hook の設定
    - include: tasks/set_git_hook.yml
      vars:
        worktree_dir: 'worktree'
