---
- hosts: ings_vps
  sudo: yes
  # 変数定義
  vars:
    www_dir: '/var/www/html'
    domain: 'xxx.xxx'
    docroot: 'htdocs'
    user: 'ings'
    group: 'apache'
    sftpuser: 'xxxx'
    sftpgroup: 'sftponly'
  # インタラクティブに聞かれる変数
  vars_prompt:
    subdomain: "Enter Subdomain Name"
    authpasswd: "Enter Basic Authentication Password"
  tasks:
    # サブドメインのディレクトリ＆ドキュメントルートのディレクトリを作成
    - include: tasks/create_root_directory.yml

    # ベーシック認証の設定
    - include: tasks/set_apache_basicauth.yml

    # ベーシック認証の設定
    - include: tasks/change_permission_root_directory.yml
