# wordpressをサブディレクトリにインストールするため、index.phpをドキュメントルートへコピー
- name: index.php copy from wordpress directory to document root
  shell: >-
    cp {{ www_dir }}/{{ subdomain }}.{{ domain }}/{{ docroot }}/{{ prefix }}/index.php {{ www_dir }}/{{ subdomain }}.{{ domain }}/{{ docroot }}/index.php
    creates={{ www_dir }}/{{ subdomain }}.{{ domain }}/{{ docroot }}/index.php
  sudo: no

# コピーしたindex.php内のパスを編集
# 前) require( dirname( __FILE__ ) . '/wp-blog-header.php' );
# 後) require( dirname( __FILE__ ) . '/wp/wp-blog-header.php' );
- name: index.php require path change
  lineinfile: >-
    dest={{ www_dir }}/{{ subdomain }}.{{ domain }}/{{ docroot }}/index.php
    state=present
    regexp='wp-blog-header.php'
    line="require( dirname( __FILE__ ) . '/{{prefix}}/wp-blog-header.php' );"
  sudo: no
