# DBの作成
- name: create database
  mysql_db: >-
    name={{ wordpress_db_name }}
    state=present
    login_user=root
    login_password={{ wordpress_root_db_pass }}
  register: db_exists
  tags: wordpress

# DBのユーザー作成、権限付与
- name: create database user
  mysql_user: >-
    name={{ wordpress_db_user }}
    password={{ wordpress_db_password }}
    priv={{ wordpress_db_name }}.*:ALL
    state=present
    login_user=root
    login_password={{ wordpress_root_db_pass }}
  tags: wordpress
